### ISSUE TITLE
Excepted got "/" (Comment support)

### ISSUE THREAD

**Issue by totyaxy** [hydrobyte/McJSON#11]
In principle, the JSON5 standard:
https://spec.json5.org/#comments
Of course, one could argue about how standard it is, but for example Json.NET supports it: https://www.newtonsoft.com/json
I don't think it's too complicated to implement, you just have to ignore it when reading:

// This is a single line comment.

/* This is a multi-
   line comment. */

**Comment by hydrobyte** [comment]
Hi,

Could you check if [fcl-json](https://wiki.freepascal.org/fcl-json) supports comments?

In my initial research, this was discarded because Delphi's [System.JSON](https://docwiki.embarcadero.com/Libraries/Alexandria/en/System.JSON) does not support comments.

**Comment by totyaxy** [comment]
Hi!

I don't think so, and I really don't, it throws an error:

uses
  fpjson, jsonparser;

{$R *.lfm}

procedure TForm1.Button1Click(Sender: TObject);
var
  jData : TJSONData;
begin
  jData := GetJSON('//');
end;

**Comment by hydrobyte** [comment]
It seems comments are controversial already.

On the other hand, I think you can parse and exclude comments before using `McJSON` or any other library.

Regards,

**Comment by totyaxy** [comment]
I think it is very easy to identify the two types of comments, and the library would not throw them away if they came across them. But I understand your point and thanks for the reply!

**Comment by hydrobyte** [comment]
I think I can create a new method called `readComment()` and then jump.

What complicates it is that comments could occur anywhere, so I have to check how many calls of this new method would be needed and also how to handle syntax errors due to comments. 

I think that's why many libraries leave this aspect out.

**Comment by totyaxy** [comment]
I thought you were reading lines when reading from a file. Only the first two characters should be examined. It's true that a row can contain multiple keys and values, but I don't think the comment makes sense within a row. Of course, you have a better understanding of how your code works.

"Does Lazarus' [fcl-json](https://wiki.freepascal.org/fcl-json) not meet your needs? I'm curious why McJSON seems more important to you than a native library."

I process around 1000 json files with tens of thousands of keys, speed is also important, and I saw the speed test that this library is very good (see readme) and fully supports Lazarus, so why not use it? :)

**Comment by hydrobyte** [comment]
Actually, after some reading:

- JSON does not have [comments](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

So, I'll close this issue.

Thanks.

**Comment by totyaxy** [comment]
Okay, but see the my first comment. :) Thanks for taking care of it!

**Comment by hydrobyte** [comment]
I saw your first comment, but I recommend you see [this](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).
