### ISSUE TITLE
Slow json generation speed

### ISSUE THREAD

**Issue by totyaxy** [hydrobyte/McJSON#14]
Presumably due to **my not quite correct code.** I create a json structure this way:

``` pascal
Json.Add(IndexStr);
for x in Tx do
  Json.Path(IndexStr).Add(x.key).AsString := McJsonEscapeString(x.value);   
```

This about look this way (about 150k line):

``` json
 "200": {
    "Key1": "Value1",
    "Key2": "Value2",
    "Key3": "Value3"
  },

 "201": {
    "Key1": "Value1",
    "Key2": "Value2",
    "Key3": "Value3"
  },
```

I think the low generation speed is because of the path usage, can this be fixed somehow? For example 
If I always write to the last one, the library doesn't need to search through the entire structure.

**Comment by hydrobyte** [comment]
Hi,

Try to leave the `Path()` call outside the loop. Actually, you don't need to call it:

````pascal
JsonIdx := Json.Add(IndexStr);
for x in Tx do
  JsonIdx.Add(x.key).AsString := McJsonEscapeString(x.value);  
````

Could you report how fast is this modification (in % or seconds/milliseconds)?

Regards,

**Comment by totyaxy** [comment]
I knew it, there is a faster way than it, thank you!

Old method: 88,5 secs
New method: 11.7 secs

It's about 800% faster way, thank you!

Maybe it's a good idea to write something similar in the wiki, because I think it's better read than "issues".

**Comment by hydrobyte** [comment]
OK

**Comment by hydrobyte** [comment]
Hi,

I've just commit a new project that might be of your interest:

https://github.com/hydrobyte/TestJSON

I'm planning to create a Lazarus version too.

Regards,

**Comment by totyaxy** [comment]
Yes, I am interested, but I can only run fpc/lazarus code. Maybe a deplhit that can be converted by lazarus.
