### ISSUE TITLE
Empty string passed Check validation.

### ISSUE THREAD

**Issue by mnabarro** [hydrobyte/McJSON#25]
Hi! Thanks for this project. I'm using it to validate json files and an empty string passes validation and I think it should not.

**Comment by hydrobyte** [comment]
Hi,

Thanks for your feedback.

See, empty values are valid as in ``{"k":""}``.

Also, empty keys are valid like this: ``{"":"v"}``.

See [JSON Lint](https://jsonlint.com/) as reference.

Regards,

Marcelo.

**Comment by mnabarro** [comment]
Thanks you for your quick response. I know that empty strings are valid but, what I was trying to say is that, if you pass an empty string to validate ( i.e.` check('')` ) it returns `true `and it should return `false`, just like JSON Lint does if you simply click on the [**Validate JSON**] button without any text in the textarea. 

Best regards.

**Comment by hydrobyte** [comment]
Oh, Now I got it.
It is simple to implement.
Meanwhile, you can check just not empty strings, right? :-)
I'll share it in next update.
Best.

**Comment by hydrobyte** [comment]
Done!
Sorry for the delay.
