### ISSUE TITLE
When value is a json string, tostring does not handle escaping

### ISSUE THREAD

**Issue by leeonsoft** [hydrobyte/McJSON#4]
When value is a json string, tostring does not handle escaping

**Comment by hydrobyte** [comment]
Could you provide a small example?

**Comment by leeonsoft** [comment]
var
  json:TMcJsonItem;
  str:string;
  JsonObject:TJsonObject;
begin
  try
    { TODO -oUser -cConsole Main : Insert code here }
    json:=TMcJsonItem.Create;
    JsonObject:=TJsonObject.Create;
    try
      json.add('topic').AsString:='test';
      json.add('content').AsString:='{"name":"111"}';
      Str:= json.ToString(false);
      writeln('mcJson:'+str);
      JsonObject.S['topic']:='test';
      JsonObject.S['content']:='{"name":"111"}';
      Str:= JsonObject.ToJSON();
      writeln('JsonObject:'+str);
      Readln;
    finally
      json.Free;
      JsonObject.Free;
    end;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.

![QQ图片20220808180252](https://user-images.githubusercontent.com/11594126/183393270-4b5eaf16-b0c8-426f-a56e-eef1be4657ed.png)

**Comment by hydrobyte** [comment]
If you provide an escaped string representing a JSON object it will work. There is an example in Test11:

'{"k":"{\"key\":\"value\"}"}'

McJSON doesn't do the escapes for you. 

However, the correct thing would be to throw an exception, since it is not being managed automatically.

I'll improve it to automatically manage this or throw an exception.

Thanks.

**Comment by leeonsoft** [comment]
I need mcjson to help me generate the correct json string so that other programs can parse it

**Comment by hydrobyte** [comment]
You can write a simple function in order to escape double quotes:

json.add('content').AsString:= MyEscapeDoubleQuotes('{"name":"111"}');
